import { SurahType } from 'types';

const surahs: SurahType[] = [
  {
    number: 1,
    name: 'Al-Fatihah',
    en: 'The Opening',
    arabic: 'الفاتحة',
    revelationType: 'Meccan',
    ayahs: 7,
  },
  {
    number: 2,
    name: 'Al-Baqarah',
    en: 'The Cow',
    arabic: 'البقرة',
    revelationType: 'Medinan',
    ayahs: 286,
  },
  {
    number: 3,
    name: 'Al-Imran',
    en: 'The Family of Imran',
    arabic: 'آل عمران',
    revelationType: 'Medinan',
    ayahs: 200,
  },
  {
    number: 4,
    name: 'An-Nisa',
    en: 'The Women',
    arabic: 'النساء',
    revelationType: 'Medinan',
    ayahs: 176,
  },
  {
    number: 5,
    name: 'Al-Ma idah',
    en: 'The Table spread with Food',
    arabic: 'المائدة',
    revelationType: 'Medinan',
    ayahs: 120,
  },
  {
    number: 6,
    name: 'Al-An am',
    en: 'The Cattle',
    arabic: 'الأنعام',
    revelationType: 'Meccan',
    ayahs: 165,
  },
  {
    number: 7,
    name: 'Al-A raf',
    en: 'The Heights',
    arabic: 'الأعراف',
    revelationType: 'Meccan',
    ayahs: 206,
  },
  {
    number: 8,
    name: 'Al-Anfal',
    en: 'The Spoils of War',
    arabic: 'الأنفال',
    revelationType: 'Medinan',
    ayahs: 75,
  },
  {
    number: 9,
    name: 'At-Tawbah',
    en: 'The Repentance',
    arabic: 'التوبة',
    revelationType: 'Medinan',
    ayahs: 129,
  },
  {
    number: 10,
    name: 'Yunus',
    en: 'Jonah',
    arabic: 'يونس',
    revelationType: 'Meccan',
    ayahs: 109,
  },
  {
    number: 11,
    name: 'Hud',
    en: 'Hud',
    arabic: 'هود',
    revelationType: 'Meccan',
    ayahs: 123,
  },
  {
    number: 12,
    name: 'Yusuf',
    en: 'Joseph',
    arabic: 'يوسف',
    revelationType: 'Meccan',
    ayahs: 111,
  },
  {
    number: 13,
    name: 'Ar-Ra d',
    en: 'The Thunder',
    arabic: 'الرعد',
    revelationType: 'Medinan',
    ayahs: 43,
  },
  {
    number: 14,
    name: 'Ibrahim',
    en: 'Abraham',
    arabic: 'إبراهيم',
    revelationType: 'Meccan',
    ayahs: 52,
  },
  {
    number: 15,
    name: 'Al-Hijr',
    en: 'The Rocky Tract',
    arabic: 'الحجر',
    revelationType: 'Meccan',
    ayahs: 99,
  },
  {
    number: 16,
    name: 'An-Nahl',
    en: 'The Bee',
    arabic: 'النحل',
    revelationType: 'Meccan',
    ayahs: 128,
  },
  {
    number: 17,
    name: 'Al-Isra',
    en: 'The Night Journey',
    arabic: 'الإسراء',
    revelationType: 'Meccan',
    ayahs: 111,
  },
  {
    number: 18,
    name: 'Al-Kahf',
    en: 'The Cave',
    arabic: 'الكهف',
    revelationType: 'Meccan',
    ayahs: 110,
  },
  {
    number: 19,
    name: 'Maryam',
    en: 'Mary',
    arabic: 'مريم',
    revelationType: 'Meccan',
    ayahs: 98,
  },
  {
    number: 20,
    name: 'Taha',
    en: 'Ta-Ha',
    arabic: 'طه',
    revelationType: 'Meccan',
    ayahs: 135,
  },
  {
    number: 21,
    name: 'Al-Anbiya',
    en: 'The Prophets',
    arabic: 'الأنبياء',
    revelationType: 'Meccan',
    ayahs: 112,
  },
  {
    number: 22,
    name: 'Al-Hajj',
    en: 'The Pilgrimage',
    arabic: 'الحج',
    revelationType: 'Medinan',
    ayahs: 78,
  },
  {
    number: 23,
    name: 'Al-Mu`minun',
    en: 'The Believers',
    arabic: 'المؤمنون',
    revelationType: 'Meccan',
    ayahs: 118,
  },
  {
    number: 24,
    name: 'An-Nur',
    en: 'The Light',
    arabic: 'النور',
    revelationType: 'Medinan',
    ayahs: 64,
  },
  {
    number: 25,
    name: 'Al-Furqan',
    en: 'The Criterion',
    arabic: 'الفرقان',
    revelationType: 'Meccan',
    ayahs: 77,
  },
  {
    number: 26,
    name: 'Ash-Shu`ara',
    en: 'The Poets',
    arabic: 'الشعراء',
    revelationType: 'Meccan',
    ayahs: 227,
  },
  {
    number: 27,
    name: 'An-Naml',
    en: 'The Ant',
    arabic: 'النمل',
    revelationType: 'Meccan',
    ayahs: 93,
  },
  {
    number: 28,
    name: 'Al-Qasas',
    en: 'The Stories',
    arabic: 'القصص',
    revelationType: 'Meccan',
    ayahs: 88,
  },
  {
    number: 29,
    name: 'Al-`Ankabut',
    en: 'The Spider',
    arabic: 'العنكبوت',
    revelationType: 'Meccan',
    ayahs: 69,
  },
  {
    number: 30,
    name: 'Ar-Rum',
    en: 'The Romans',
    arabic: 'الروم',
    revelationType: 'Meccan',
    ayahs: 60,
  },
  {
    number: 31,
    name: 'Luqman',
    en: 'Luqman',
    arabic: 'لقمان',
    revelationType: 'Meccan',
    ayahs: 34,
  },
  {
    number: 32,
    name: 'As-Sajdah',
    en: 'The Prostration',
    arabic: 'السجدة',
    revelationType: 'Meccan',
    ayahs: 30,
  },
  {
    number: 33,
    name: 'Al-Ahzab',
    en: 'The Combined Forces',
    arabic: 'الأحزاب',
    revelationType: 'Medinan',
    ayahs: 73,
  },
  {
    number: 34,
    name: 'Saba',
    en: 'Sheba',
    arabic: 'سبإ',
    revelationType: 'Meccan',
    ayahs: 54,
  },
  {
    number: 35,
    name: 'Fatir',
    en: 'The Originator',
    arabic: 'فاطر',
    revelationType: 'Meccan',
    ayahs: 45,
  },
  {
    number: 36,
    name: 'Ya-Sin',
    en: 'Ya Sin',
    arabic: 'يس',
    revelationType: 'Meccan',
    ayahs: 83,
  },
  {
    number: 37,
    name: 'As-Saffat',
    en: 'Those Who Set The Ranks',
    arabic: 'الصافات',
    revelationType: 'Meccan',
    ayahs: 182,
  },
  {
    number: 38,
    name: 'Sad',
    en: 'The Letter "Saad"',
    arabic: 'ص',
    revelationType: 'Meccan',
    ayahs: 88,
  },
  {
    number: 39,
    name: 'Az-Zumar',
    en: 'The Groups',
    arabic: 'الزمر',
    revelationType: 'Meccan',
    ayahs: 75,
  },
  {
    number: 40,
    name: 'Ghafir',
    en: 'The Forgiver',
    arabic: 'غافر',
    revelationType: 'Meccan',
    ayahs: 85,
  },
  {
    number: 41,
    name: 'Fussilat',
    en: 'Explained in Detail',
    arabic: 'فصلت',
    revelationType: 'Meccan',
    ayahs: 54,
  },
  {
    number: 42,
    name: 'Ash-Shura',
    en: 'Consultation',
    arabic: 'الشورى',
    revelationType: 'Meccan',
    ayahs: 53,
  },
  {
    number: 43,
    name: 'Az-Zukhruf',
    en: 'The Gold Adornments',
    arabic: 'الزخرف',
    revelationType: 'Meccan',
    ayahs: 89,
  },
  {
    number: 44,
    name: 'Ad-Dukhan',
    en: 'The Smoke',
    arabic: 'الدخان',
    revelationType: 'Meccan',
    ayahs: 59,
  },
  {
    number: 45,
    name: 'Al-Jathiya',
    en: 'The Kneeling',
    arabic: 'الجاثية',
    revelationType: 'Meccan',
    ayahs: 37,
  },
  {
    number: 46,
    name: 'Al-Ahqaf',
    en: 'The Curved Sand-hills',
    arabic: 'الأحقاف',
    revelationType: 'Meccan',
    ayahs: 35,
  },
  {
    number: 47,
    name: 'Muhammad',
    en: 'Muhammad',
    arabic: 'محمد',
    revelationType: 'Medinan',
    ayahs: 38,
  },
  {
    number: 48,
    name: 'Al-Fath',
    en: 'The Victory',
    arabic: 'الفتح',
    revelationType: 'Medinan',
    ayahs: 29,
  },
  {
    number: 49,
    name: 'Al-Hujurat',
    en: 'The Rooms',
    arabic: 'الحجرات',
    revelationType: 'Medinan',
    ayahs: 18,
  },
  {
    number: 50,
    name: 'Qaf',
    en: 'The Letter "Qaf"',
    arabic: 'ق',
    revelationType: 'Meccan',
    ayahs: 45,
  },
  {
    number: 51,
    name: 'Adh-Dhariyat',
    en: 'The Winnowing Winds',
    arabic: 'الذاريات',
    revelationType: 'Meccan',
    ayahs: 60,
  },
  {
    number: 52,
    name: 'At-Tur',
    en: 'The Mount',
    arabic: 'الطور',
    revelationType: 'Meccan',
    ayahs: 49,
  },
  {
    number: 53,
    name: 'An-Najm',
    en: 'The Star',
    arabic: 'النجم',
    revelationType: 'Meccan',
    ayahs: 62,
  },
  {
    number: 54,
    name: 'Al-Qamar',
    en: 'The Moon',
    arabic: 'القمر',
    revelationType: 'Meccan',
    ayahs: 55,
  },
  {
    number: 55,
    name: 'Ar-Rahman',
    en: 'The Most Merciful',
    arabic: 'الرحمن',
    revelationType: 'Medinan',
    ayahs: 78,
  },
  {
    number: 56,
    name: "Al-Waqi'ah",
    en: 'The Inevitable',
    arabic: 'الواقعة',
    revelationType: 'Meccan',
    ayahs: 96,
  },
  {
    number: 57,
    name: 'Al-Hadid',
    en: 'The Iron',
    arabic: 'الحديد',
    revelationType: 'Medinan',
    ayahs: 29,
  },
  {
    number: 58,
    name: 'Al-Mujadilah',
    en: 'The Pleading Woman',
    arabic: 'المجادلة',
    revelationType: 'Medinan',
    ayahs: 22,
  },
  {
    number: 59,
    name: 'Al-Hashr',
    en: 'The Exile',
    arabic: 'الحشر',
    revelationType: 'Medinan',
    ayahs: 24,
  },
  {
    number: 60,
    name: 'Al-Mumtahanah',
    en: 'The Tested One',
    arabic: 'الممتحنة',
    revelationType: 'Medinan',
    ayahs: 13,
  },
  {
    number: 61,
    name: 'As-Saff',
    en: 'The Ranks',
    arabic: 'الصفّ',
    revelationType: 'Medinan',
    ayahs: 14,
  },
  {
    number: 62,
    name: "Al-Jumu'ah",
    en: 'Friday',
    arabic: 'الجمعة',
    revelationType: 'Medinan',
    ayahs: 11,
  },
  {
    number: 63,
    name: 'Al-Munafiqoon',
    en: 'The Hypocrites',
    arabic: 'المنافقون',
    revelationType: 'Medinan',
    ayahs: 11,
  },
  {
    number: 64,
    name: 'At-Taghabun',
    en: 'Mutual Loss and Gain',
    arabic: 'التغابن',
    revelationType: 'Medinan',
    ayahs: 18,
  },
  {
    number: 65,
    name: 'At-Talaq',
    en: 'Divorce',
    arabic: 'الطلاق',
    revelationType: 'Medinan',
    ayahs: 12,
  },
  {
    number: 66,
    name: 'At-Tahrim',
    en: 'The Prohibition',
    arabic: 'التحريم',
    revelationType: 'Medinan',
    ayahs: 12,
  },
  {
    number: 67,
    name: 'Al-Mulk',
    en: 'The Sovereignty',
    arabic: 'الملك',
    revelationType: 'Meccan',
    ayahs: 30,
  },
  {
    number: 68,
    name: 'Al-Qalam',
    en: 'The Pen',
    arabic: 'القلم',
    revelationType: 'Meccan',
    ayahs: 52,
  },
  {
    number: 69,
    name: 'Al-Haaqqa',
    en: 'The Reality',
    arabic: 'الحاقة',
    revelationType: 'Meccan',
    ayahs: 52,
  },
  {
    number: 70,
    name: 'Al-Maarij',
    en: 'The Ascending Stairways',
    arabic: 'المعارج',
    revelationType: 'Meccan',
    ayahs: 44,
  },
  {
    number: 71,
    name: 'Nooh',
    en: 'Noah',
    arabic: 'نوح',
    revelationType: 'Meccan',
    ayahs: 28,
  },
  {
    number: 72,
    name: 'Al-Jinn',
    en: 'The Jinn',
    arabic: 'الجن',
    revelationType: 'Meccan',
    ayahs: 28,
  },
  {
    number: 73,
    name: 'Al-Muzzammil',
    en: 'The Enshrouded One',
    arabic: 'المزمل',
    revelationType: 'Meccan',
    ayahs: 20,
  },
  {
    number: 74,
    name: 'Al-Muddaththir',
    en: 'The Cloaked One',
    arabic: 'المدثر',
    revelationType: 'Meccan',
    ayahs: 56,
  },
  {
    number: 75,
    name: 'Al-Qiyama',
    en: 'The Resurrection',
    arabic: 'القيامة',
    revelationType: 'Meccan',
    ayahs: 40,
  },
  {
    number: 76,
    name: 'Al-Insan',
    en: 'Man',
    arabic: 'الإنسان',
    revelationType: 'Medinan',
    ayahs: 31,
  },
  {
    number: 77,
    name: 'Al-Mursalat',
    en: 'The Emissaries',
    arabic: 'المرسلات',
    revelationType: 'Meccan',
    ayahs: 50,
  },
  {
    number: 78,
    name: 'An-Naba',
    en: 'The Tidings',
    arabic: 'النبإ',
    revelationType: 'Meccan',
    ayahs: 40,
  },
  {
    number: 79,
    name: "An-Nazi'at",
    en: 'Those who drag forth',
    arabic: 'النازعات',
    revelationType: 'Meccan',
    ayahs: 46,
  },
  {
    number: 80,
    name: 'Abasa',
    en: 'He Frowned',
    arabic: 'عبس',
    revelationType: 'Meccan',
    ayahs: 42,
  },
  {
    number: 81,
    name: 'At-Takwir',
    en: 'The Overthrowing',
    arabic: 'التكوير',
    revelationType: 'Meccan',
    ayahs: 29,
  },
  {
    number: 82,
    name: 'Al-Infitar',
    en: 'The Cleaving',
    arabic: 'الإنفطار',
    revelationType: 'Meccan',
    ayahs: 19,
  },
  {
    number: 83,
    name: 'Al-Mutaffifin',
    en: 'The Defrauders',
    arabic: 'المطففين',
    revelationType: 'Meccan',
    ayahs: 36,
  },
  {
    number: 84,
    name: 'Al-Inshiqaq',
    en: 'The Splitting Open',
    arabic: 'الإنشقاق',
    revelationType: 'Meccan',
    ayahs: 25,
  },
  {
    number: 85,
    name: 'Al-Buruj',
    en: 'The Constellations',
    arabic: 'البروج',
    revelationType: 'Meccan',
    ayahs: 22,
  },
  {
    number: 86,
    name: 'At-Tariq',
    en: 'The Morning Star',
    arabic: 'الطارق',
    revelationType: 'Meccan',
    ayahs: 17,
  },
  {
    number: 87,
    name: "Al-A'la",
    en: 'The Most High',
    arabic: 'الأعلى',
    revelationType: 'Meccan',
    ayahs: 19,
  },
  {
    number: 88,
    name: 'Al-Ghashiyah',
    en: 'The Overwhelming Event',
    arabic: 'الغاشية',
    revelationType: 'Meccan',
    ayahs: 26,
  },
  {
    number: 89,
    name: 'Al-Fajr',
    en: 'The Dawn',
    arabic: 'الفجر',
    revelationType: 'Meccan',
    ayahs: 30,
  },
  {
    number: 90,
    name: 'Al-Balad',
    en: 'The City',
    arabic: 'البلد',
    revelationType: 'Meccan',
    ayahs: 20,
  },
  {
    number: 91,
    name: 'Ash-Shams',
    en: 'The Sun',
    arabic: 'الشمس',
    revelationType: 'Meccan',
    ayahs: 15,
  },
  {
    number: 92,
    name: 'Al-Lail',
    en: 'The Night',
    arabic: 'الليل',
    revelationType: 'Meccan',
    ayahs: 21,
  },
  {
    number: 93,
    name: 'Ad-Duhaa',
    en: 'The Morning Hours',
    arabic: 'الضحى',
    revelationType: 'Meccan',
    ayahs: 11,
  },
  {
    number: 94,
    name: 'Ash-Sharh',
    en: 'The Consolation',
    arabic: 'الشرح',
    revelationType: 'Meccan',
    ayahs: 8,
  },
  {
    number: 95,
    name: 'At-Tin',
    en: 'The Fig',
    arabic: 'التين',
    revelationType: 'Meccan',
    ayahs: 8,
  },
  {
    number: 96,
    name: 'Al-Alaq',
    en: 'The Clot',
    arabic: 'العلق',
    revelationType: 'Meccan',
    ayahs: 19,
  },
  {
    number: 97,
    name: 'Al-Qadr',
    en: 'The Power, Fate',
    arabic: 'القدر',
    revelationType: 'Meccan',
    ayahs: 5,
  },
  {
    number: 98,
    name: 'Al-Bayyinah',
    en: 'The Clear Proof',
    arabic: 'البينة',
    revelationType: 'Medinan',
    ayahs: 8,
  },
  {
    number: 99,
    name: 'Az-Zalzalah',
    en: 'The Earthquake',
    arabic: 'الزلزلة',
    revelationType: 'Medinan',
    ayahs: 8,
  },
  {
    number: 100,
    name: 'Al-Adiyat',
    en: 'The Chargers',
    arabic: 'العاديات',
    revelationType: 'Meccan',
    ayahs: 11,
  },
  {
    number: 101,
    name: 'Al-Qariah',
    en: 'The Calamity',
    arabic: 'القارعة',
    revelationType: 'Meccan',
    ayahs: 11,
  },
  {
    number: 102,
    name: 'At-Takathur',
    en: 'The Piling Up',
    arabic: 'التكاثر',
    revelationType: 'Meccan',
    ayahs: 8,
  },
  {
    number: 103,
    name: 'Al-Asr',
    en: 'The Time',
    arabic: 'العصر',
    revelationType: 'Meccan',
    ayahs: 3,
  },
  {
    number: 104,
    name: 'Al-Humazah',
    en: 'The Slanderer',
    arabic: 'الهمزة',
    revelationType: 'Meccan',
    ayahs: 9,
  },
  {
    number: 105,
    name: 'Al-Fil',
    en: 'The Elephant',
    arabic: 'الفيل',
    revelationType: 'Meccan',
    ayahs: 5,
  },
  {
    number: 106,
    name: 'Quraish',
    en: 'Quraish',
    arabic: 'قريش',
    revelationType: 'Meccan',
    ayahs: 4,
  },
  {
    number: 107,
    name: 'Al-Maun',
    en: 'The Small Kindnesses',
    arabic: 'الماعون',
    revelationType: 'Meccan',
    ayahs: 7,
  },
  {
    number: 108,
    name: 'Al-Kauthar',
    en: 'The Abundance',
    arabic: 'الكوثر',
    revelationType: 'Meccan',
    ayahs: 3,
  },
  {
    number: 109,
    name: 'Al-Kafirun',
    en: 'The Disbelievers',
    arabic: 'الكافرون',
    revelationType: 'Meccan',
    ayahs: 6,
  },
  {
    number: 110,
    name: 'An-Nasr',
    en: 'The Help',
    arabic: 'النصر',
    revelationType: 'Medinan',
    ayahs: 3,
  },
  {
    number: 111,
    name: 'Al-Masad',
    en: 'The Palm Fiber',
    arabic: 'المسد',
    revelationType: 'Meccan',
    ayahs: 5,
  },
  {
    number: 112,
    name: 'Al-Ikhlas',
    en: 'The Sincerity',
    arabic: 'الإخلاص',
    revelationType: 'Meccan',
    ayahs: 4,
  },
  {
    number: 113,
    name: 'Al-Falaq',
    en: 'The Dawn',
    arabic: 'الفلق',
    revelationType: 'Meccan',
    ayahs: 5,
  },
  {
    number: 114,
    name: 'An-Nas',
    en: 'The Men',
    arabic: 'الناس',
    revelationType: 'Meccan',
    ayahs: 6,
  },
];

export { surahs };
